image: registry.gitlab.com/skaginn3x/tfc/framework/archlinux-cpp:latest

stages:
- build
- check
- test
- deploy

variables:
  VCPKG_BINARY_SOURCES: "http,${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/{name}/{version}/{sha}.zip,readwrite,Authorization: Bearer $CI_JOB_TOKEN"

build:
  stage: build
  script:
    - cmake --preset ci-clang-debug
    - cmake --build --preset build-ci-clang-debug
  artifacts:
    paths:
      - build/

check:cpp:format:
  stage: check
  script: find libs/ exes/ \( -name \*.cpp -o -name \*.hpp \) -print0 | xargs -0 -n 1 clang-format --Werror --verbose --dry-run

test:ctest:
  stage: test
  dependencies:
    - build
  script:
    # It looks like --test-dir sets the working directory for ctest. junit_ctest.xml is therefor inside the build dir.
    - ctest --test-dir build/ci-clang-debug --output-on-failure --output-junit junit_ctest.xml
  artifacts:
    when: always
    paths:
      - build/dev-clang-debug-dynamic/junit_ctest.xml
    reports:
      junit: build/dev-clang-debug-dynamic/junit_ctest.xml

pages:
  stage: deploy
  script:
    # Package the public data from the build nicely
    - mkdir -p public/$CI_COMMIT_BRANCH
    - cp -r build/ci-clang-debug/docs/doxygen/html public/$CI_COMMIT_BRANCH/doxygen
    # RTD is the default landing page for pages
    - cp -r build/ci-clang-debug/docs/sphinx/* public/$CI_COMMIT_BRANCH/
  dependencies:
    - build
    - test:ctest
  artifacts:
    paths:
      - public

oci_container_build_archlinux_cpp:
  image: quay.io/buildah/stable
  stage: build
  variables:
    DOCKERFILE_NAME: "archlinux-cpp"
    FQ_IMAGE_NAME: "archlinux-cpp:latest"
  before_script:
    - buildah version
  script:
    - echo ${CI_REGISTRY_IMAGE}/${FQ_IMAGE_NAME}
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - buildah bud -f containers/${DOCKERFILE_NAME} -t ${DOCKERFILE_NAME} .
    - CONTAINER_ID=$(buildah from ${DOCKERFILE_NAME})
    - buildah commit --squash $CONTAINER_ID $FQ_IMAGE_NAME
    - echo $FQ_IMAGE_NAME
    - buildah push ${FQ_IMAGE_NAME} ${CI_REGISTRY_IMAGE}/${FQ_IMAGE_NAME}
  when: manual
