image: registry.gitlab.com/skaginn3x/tfc/framework/archlinux-cpp:latest

stages:
- build
- test
- deploy

variables:
  VCPKG_BINARY_SOURCES: "http,${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/{name}/{version}/{sha}.zip,readwrite,Authorization: Bearer $CI_JOB_TOKEN"

build:
  stage: build
  script:
    - cmake --preset ci-clang-debug
    - cmake --build --preset build-ci-clang-debug
  artifacts:
    paths:
      - build/

runCtest:
  stage: test
  dependencies:
    - build
  script:
    # It looks like --test-dir sets the working directory for ctest. junit_ctest.xml is therefor inside the build dir.
    - ctest --test-dir build/ci-clang-debug --output-on-failure --output-junit junit_ctest.xml
  artifacts:
    when: always
    paths:
      - build/dev-clang-debug-dynamic/junit_ctest.xml
    reports:
      junit: build/dev-clang-debug-dynamic/junit_ctest.xml

pages:
  stage: deploy
  script:
    # Package the public data from the build nicely
    - mkdir -p public/$CI_COMMIT_BRANCH
    - cp -r build/ci-clang-debug/docs/doxygen/html public/$CI_COMMIT_BRANCH/doxygen
    # RTD is the default landing page for pages
    - cp -r build/ci-clang-debug/docs/sphinx/* public/$CI_COMMIT_BRANCH/
  dependencies:
    - build
    - runCtest
  artifacts:
    paths:
      - public
