set(CMAKE_SYSTEM_PROCESSOR x64)
find_program(CLANG-16 "clang-16")
if(CLANG-16)
  set(CMAKE_C_COMPILER clang-16)
  set(CMAKE_CXX_COMPILER clang++-16)
  set(CMAKE_CXX_FLAGS "-stdlib=libc++")
else()
  set(CMAKE_C_COMPILER /opt/clang-16.0.0/bin/clang)
  set(CMAKE_CXX_COMPILER /opt/clang-16.0.0/bin/clang++)
  set(CMAKE_CXX_FLAGS "-stdlib=libc++ -I/opt/clang-16.0.0/include/ -I/opt/clang-16.0.0/include/x86_64-unknown-linux-gnu/c++/v1")
endif()
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
