set(CMAKE_SYSTEM_PROCESSOR x64)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_FLAGS "-stdlib=libc++ -I/cpproot/include/x86_64-unknown-linux-gnu/c++/v1/ -I/cpproot/include/c++/v1")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld")
