set(CMAKE_SYSTEM_PROCESSOR x64)
set(CMAKE_C_COMPILER /cpproot/bin/clang)
set(CMAKE_CXX_COMPILER /cpproot/bin/clang++)
set(CMAKE_CXX_FLAGS "-stdlib=libc++ -I/cpproot/include/")
set(CMAKE_C_FLAGS "")
set(LINK_FLAGS -fuse-ld=lld)
set(STATIC_LIBRARY_FLAGS -fuse-ld=lld)
