set(CMAKE_SYSTEM_PROCESSOR x64)
find_program(GCC-12 "gcc-12")
if(GCC-12)
  set(CMAKE_C_COMPILER gcc-12)
  set(CMAKE_CXX_COMPILER g++-12)
else()
  set(CMAKE_C_COMPILER gcc)
  set(CMAKE_CXX_COMPILER g++)
endif()
