#!/usr/bin/env python3
import subprocess
import os
import shutil
import sys

def create_user(name, shell="/bin/bash", user_id=1000, group_id=1000):
  try:
      subprocess.run(["groupadd", "-r", name], check=True)
      subprocess.run(["useradd", "-r", "-g", name, "-s", shell, name], check=True)
  except subprocess.CalledProcessError:
      print("User already exists, skipping creation")


if __name__ == "__main__":
  if os.getuid() != 0:
    print("Please run this script as root!", file=sys.stderr)
    exit -10

  user_name = "tfc"
  print("Creating user: {}".format(user_name))
  create_user(user_name, shell="/sbin/nologin")

  print("Creating directories for tfc")
  os.makedirs("/etc/tfc", exist_ok=True, mode=0o775)
  shutil.chown("/etc/tfc", user_name, user_name)

  os.makedirs("/var/tfc", exist_ok=True, mode=0o775)
  shutil.chown("/var/tfc", user_name, user_name)

  os.makedirs("/run/tfc", exist_ok=True, mode=0o775)
  shutil.chown("/run/tfc", user_name, user_name)

  os.makedirs("/var/log/tfc", exist_ok=True, mode=0o775)
  shutil.chown("/var/log/tfc", user_name, user_name)
