function(tfc_install_lib TARGET)
  include(GNUInstallDirs)
  ##### install(TARGETS ${TARGET}
  #####   EXPORT tfcTargets
  #####   LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  #####   ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  #####   RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
  #####   PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  #####   BUNDLE DESTINATION ${CMAKE_INSTALL_BINDIR}
  ##### )
  ##### install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/inc/public/ DESTINATION include)
endfunction()
