function(tfc_install_lib_impl TARGET INCLUDE_DIR)
  include(GNUInstallDirs)
  install(TARGETS ${TARGET}
    EXPORT tfcTargets
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    BUNDLE DESTINATION ${CMAKE_INSTALL_BINDIR}
  )
  install(DIRECTORY ${INCLUDE_DIR} DESTINATION include)
endfunction()

function(tfc_install_lib TARGET)
  tfc_install_lib_impl(${TARGET} ${CMAKE_CURRENT_SOURCE_DIR}/inc/public/)
endfunction()

