name: alpine static

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_static_artifacts:
    runs-on: ubuntu-22.04
    name: Build static artifacts
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
        id: alpine
        name: Alpine maker
        with:
          branch: v3.17
          packages: >
            g++ curl zip unzip tar build-base musl python3 cmake make linux-headers openssl-dev git rpm-dev
            doxygen py3-sphinx py3-breathe py3-myst-parser py3-sphinx_rtd_theme graphviz
      - name: Get new cmake
        run: |
          apk add cmake --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main/
        shell: alpine.sh --root {0}

      - name: Build ninja
        run: |
          VERSION=1.11.1
          curl -L https://github.com/ninja-build/ninja/archive/v$VERSION.tar.gz | tar xzf -
          cd ninja-$VERSION
          cmake -B build-cmake -S .
          cmake --build build-cmake
          cmake --install build-cmake
          cd ..
          rm -rf ninja-$VERSION
        shell: alpine.sh --root {0}

      - name: Hacking alpine virtual env
        run: | 
          ln -s /bin/sh /usr/bin/sh
          ln -s /usr/bin/cmake /usr/local/bin/cmake
        shell: alpine.sh --root {0}

#      - name: commissioning
#        run: |
#          sudo ./scripts/commissioning.sh
#          sudo chown $USER:$USER -R /var/tfc  # todo fix this differently
#          sudo chown $USER:$USER -R /run/tfc
#        shell: alpine.sh --root {0}

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11
        with:
          useShell: ${{ steps.alpine.outputs.root-path }}/abin/alpine.sh
#          vcpkgDirectory: '${{ steps.alpine.outputs.root-path }}/opt/vcpkg'
          # If not using a submodule for vcpkg sources, this specifies which commit
          # id must be checkout from a Git repo. It must not set if using a submodule
          # for vcpkg.
          vcpkgGitCommitId: '19af97cba8ca48474e4ad15a24ed50271a9ecdac'
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Run raw cmake
        run: |
          python --version
          echo version
          ls /usr/lib/
          echo breathe
          python -m breathe
          echo foo
          cmake --workflow --preset packflow-gcc-debug
        shell: alpine.sh {0}

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10.3
        with:
          useShell: ${{ steps.alpine.outputs.root-path }}/abin/alpine.sh
#          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
#          configurePreset: 'docs-gcc-debug'
#          buildPreset: 'build-ci-${{ matrix.compiler }}-${{matrix.build_type}}'
#          testPreset: 'test-ci-${{ matrix.compiler }}-${{matrix.build_type}}'
          workflowPreset: packflow-gcc-debug
