name: ci-container-build
on:
  workflow_dispatch:

env:
  IMAGE_NAME: archlinux-ci
  IMAGE_TAGS: v1 ${{ github.sha }}
  IMAGE_REGISTRY: docker://ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
      - id: string
        uses: Entepotenz/change-string-case-action-min-dependencies@v1
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - uses: actions/checkout@v3
      - name: Buildah build ci image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./containers/archlinux-cpp

      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.string.outputs.lowercase }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"