name: clang-format

on:
  push:
    branches:
      - main
      - feature/*
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: 'clang format'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DoozyX/clang-format-lint-action@v0.16.2
        with:
          source: '.'
          exclude: ''
          extensions: 'h,hpp,cpp'
          clangFormatVersion: 16
          style: file
          inplace: True
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}