name: Code checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  VCPKG_BINARY_SOURCES: clear;x-gha,readwrite

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: CMake configure
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg /opt/vcpkg
          cmake --preset ci-static-analysis

      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/build/compile_commands.json

      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
