name: compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIGURATION_DIRECTORY: ${{ github.workspace }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build and run tests'
    runs-on: ubuntu-22.04
    container: ghcr.io/skaginn3x/skaginn3x/framework/tfc-toolchain:sha-a9cc12c
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
      - name: start dbus
        run: |
          dbus-daemon --system

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '/opt/vcpkg'
          vcpkgGitCommitId: 'c9e2aa851e987698519f58518aa16564af3a85ab'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ci-${{ matrix.compiler }}-${{matrix.build_type}}'
          buildPreset: 'build-ci-${{ matrix.compiler }}-${{matrix.build_type}}'
          testPreset: 'test-ci-${{ matrix.compiler }}-${{matrix.build_type}}'
