name: docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 'build documentation'
    runs-on: ubuntu-latest
    container: ghcr.io/skaginn3x/skaginn3x/framework/tfc-toolchain:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '/opt/vcpkg'
          vcpkgGitCommitId: 'a34c873a9717a888f58dc05268dea15592c2f0ff'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Build
        run: |
          cmake --workflow --preset workflow-docs

      - name: Upload read the docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build/pack-gcc-debug/docs/sphinx'
          retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main'
    name: 'Deploy github pages'
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
