name: gcc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: 'build and run tests'
    runs-on: skaginn3x/archlinux-ci
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsystemd-dev cppcheck 
      - uses: actions/checkout@v3
      - name: commissioning
        run: |
          sudo ./scripts/commissioning.sh
          sudo chown $USER:$USER -R /var/tfc  # todo fix this differently
          sudo chown $USER:$USER -R /run/tfc

      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '/opt/vcpkg'
          # If not using a submodule for vcpkg sources, this specifies which commit
          # id must be checkout from a Git repo. It must not set if using a submodule
          # for vcpkg.
          vcpkgGitCommitId: '19af97cba8ca48474e4ad15a24ed50271a9ecdac'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ci-gcc-${{matrix.build_type}}'
          buildPreset: 'build-ci-gcc-${{matrix.build_type}}'
          testPreset: 'test-ci-gcc-${{matrix.build_type}}'

#      - name: Run static analysis
#        uses: JacobDomagala/StaticAnalysis@master
#        with:
#          use_cmake: true
#
#          # (Optional) clang-tidy args
#          clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type'
#
#          # (Optional) cppcheck args
#          cppcheck_args: --enable=all --suppress=missingInclude