name: Static analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run static analysis
        uses: JacobDomagala/StaticAnalysis@master
        with:
          use_cmake: true
          cmake_args: --preset ci-clang-debug

          apt_pckgs: cppcheck lsb-release wget software-properties-common gnupg g++-12 curl ninja-build autoconf-archive libtool autoconf meson gperf autopoint

#          init_script: curl https://apt.llvm.org/llvm.sh -o llvm.sh && chmod +x llvm.sh && ./llvm.sh 16 all

          # (Optional) clang-tidy args
          clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type'

          # (Optional) cppcheck args
          cppcheck_args: --enable=all --suppress=missingInclude