name: ubuntu packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIGURATION_DIRECTORY: ${{ github.workspace }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ubuntu packaging
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
        architecture: [ x86_64, aarch64 ]
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl zip unzip tar wget lsb-release gnupg cppcheck software-properties-common g++-12 g++-12-aarch64-linux-gnu ninja-build autoconf autoconf-archive meson gperf libcap-dev pkg-config libtool rpm autopoint doxygen python3-sphinx python3-sphinx-rtd-theme python3-breathe graphviz python3-myst-parser
          sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -s /usr/bin/aarch64-linux-gnu-g++-12 /usr/bin/aarch64-linux-gnu-g++

      - uses: actions/checkout@v3
      - name: commissioning
        run: |
          sudo ./scripts/commissioning.sh
          sudo chown $USER:$USER -R /var/tfc  # todo fix this differently
          sudo chown $USER:$USER -R /run/tfc
          sudo sed -i 's|deny own=|allow own=|g' /usr/share/dbus-1/system.conf
          sudo sed -i 's|deny send_type="method_call"|allow send_type="method_call"|g' /usr/share/dbus-1/system.conf
          sudo dbus-send --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '4eda0e3c7062e61dd89a91357ddc50f742da75ef'
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        if: matrix.architecture == 'x86_64'
        uses: lukka/run-cmake@v10.3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          workflowPreset: 'packflow-gcc-${{matrix.build_type}}'

      - name: Pack it aarch64
        if: matrix.architecture == 'aarch64'
        uses: lukka/run-cmake@v10.3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          workflowPreset: 'packflow-aarch64-gcc-${{matrix.build_type}}'

      - name: Upload vcpkg log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-build-fail-logs
          path: ${{ github.workspace }}/vcpkg/**/*out.log
      - name: Upload vcpkg log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-build-fail-logs
          path: ${{ github.workspace }}/vcpkg/**/*err.log

      - name: Test install
        if: matrix.architecture == 'x86_64'
        run: |
          sudo apt-get install ./build/pack-gcc-${{matrix.build_type}}/*.deb

      - name: Upload debian package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.deb
      - name: Upload rpm package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.rpm
      - name: Upload tar package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.tar.gz

      - name: Upload debian package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.deb
      - name: Upload rpm package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.rpm
      - name: Upload tar package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.tar.gz
