name: ubuntu packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ubuntu packaging
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
        architecture: [ x86_64, aarch64 ]
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsystemd-dev cppcheck lsb-release wget software-properties-common gnupg g++-12 g++-12-aarch64-linux-gnu curl ninja-build autoconf-archive doxygen python3-sphinx python3-sphinx-rtd-theme python3-breathe graphviz python3-myst-parser
          sudo ln -s /usr/bin/aarch64-linux-gnu-gcc-12 /usr/bin/aarch64-linux-gnu-gcc
          sudo ln -s /usr/bin/aarch64-linux-gnu-g++-12 /usr/bin/aarch64-linux-gnu-g++

      - uses: actions/checkout@v3
      - name: commissioning
        run: |
          sudo ./scripts/commissioning.sh
          sudo chown $USER:$USER -R /var/tfc  # todo fix this differently
          sudo chown $USER:$USER -R /run/tfc
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          # If not using a submodule for vcpkg sources, this specifies which commit
          # id must be checkout from a Git repo. It must not set if using a submodule
          # for vcpkg.
          vcpkgGitCommitId: '19af97cba8ca48474e4ad15a24ed50271a9ecdac'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        if: matrix.architecture == 'x86_64'
        uses: lukka/run-cmake@v10.3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          workflowPreset: 'packflow-gcc-${{matrix.build_type}}'

      - name: Pack it aarch64
        if: matrix.architecture == 'aarch64'
        uses: lukka/run-cmake@v10.3
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          workflowPreset: 'packflow-aarch64-gcc-${{matrix.build_type}}'

      - name: Test install
        if: matrix.architecture == 'x86_64'
        run: |
          sudo apt-get install ./build/pack-gcc-${{matrix.build_type}}/*.deb

      - name: Upload debian package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.deb
      - name: Upload rpm package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.rpm
      - name: Upload tar package
        if: matrix.architecture == 'x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-gcc-${{matrix.build_type}}/*.tar.gz

      - name: Upload debian package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.deb
      - name: Upload rpm package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.rpm
      - name: Upload tar package
        if: matrix.architecture == 'aarch64'
        uses: actions/upload-artifact@v3
        with:
          name: tfc-framework-${{matrix.build_type}}
          path: build/pack-aarch64-gcc-${{matrix.build_type}}/*.tar.gz
