name: vcpkg install tfc-framework

on:
  push:
    branches: [ "main" ]

env:
  CONFIGURATION_DIRECTORY: ${{ github.workspace }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'build and install'
    runs-on: ubuntu-22.04
    container: ghcr.io/skaginn3x/skaginn3x/framework/tfc-toolchain:sha-f8ab815
    strategy:
      fail-fast: false
      matrix:
        triplet: [x64-linux-gcc, x64-linux-clang, arm64-linux, x64-linux-gcc-dynamic, x64-linux-clang-dynamic]
    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest
      - name: Install tfc-framework with vcpkg
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
        with:
          runVcpkgInstall: true
          vcpkgDirectory: '/opt/vcpkg'
          vcpkgGitCommitId: 'be2d7f886aad895e282b59088a2dfca5f6e1c88a'
          vcpkgJsonGlob: 'vcpkg-test/vcpkg.json'

      - name: Upload vcpkg log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-build-fail-logs
          path: /opt/vcpkg/**/*out.log
      - name: Upload vcpkg log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: vcpkg-build-fail-logs
          path: /opt/vcpkg/**/*err.log
